title: Prantsuse-keel
description: Answers to French language exercises
theme: just-the-docs

# baseurl: ""
# url: ""

aux_links:
  Source code on Github: https://github.com/ebarrier/prantsuse-keel

color_scheme: dark
